#!/bin/bash
set -x

cp cdc3.initd /etc/init.d/cdc3

ln -s /etc/init.d/cdc3 /etc/rc0.d/K03cdc3
ln -s /etc/init.d/cdc3 /etc/rc1.d/K03cdc3
ln -s /etc/init.d/cdc3 /etc/rc2.d/S03cdc3
ln -s /etc/init.d/cdc3 /etc/rc3.d/S03cdc3
ln -s /etc/init.d/cdc3 /etc/rc4.d/S03cdc3
ln -s /etc/init.d/cdc3 /etc/rc5.d/S03cdc3
ln -s /etc/init.d/cdc3 /etc/rc6.d/K03cdc3

